baseChangeAmount: 1.1
xpEarnedByAcrobatics: 1
xpEarnedByArchery: 5
xpEarnedByExcavation: 1
xpEarnedByFarming: 5
xpEarnedByMining: 1
xpEarnedBySwords: 5
xpEarnedByUnarmed: 5
xpEarnedByWoodcutting: 1
baseMineLevelXp: 500
baseCombatLevelXp: 500
baseFarmingLevelXp: 500
skillAcrobaticsImageURL: ""
skillArcheryImageURL: ""
skillExcavationImageURL: ""
skillFarmingImageURL: ""
skillMiningImageURL: ""
skillSwordsImageURL: ""
skillUnarmedImageURL: ""
skillWoodcuttingImageURL: ""
mining-3: # On Mining Level 3
  command: "effect {PLAYER} haste {PERM} 2"
  tip: "&eGained Haste 2 forever!"
swords-5: # On Swords Level 10
  command: "effect {PLAYER} strength {PERM} 2"
  tip: "&eGained Strength 2 forever!"
farming-10: # On Farming Level 10
  command: "give {PLAYER} 351:15 32"
  tip: "&eGiven Bone Meal! (32)"